 image: Ubuntu1804 

 environment:
  nodejs_version: "node 14"

install:
  - npm install

build_script:
  - npm run build

deploy_script:
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose

after_deploy:
  - echo Deployed!